default:
  image: 'cimg/node:lts'

include:
  - project: 'ci-cd/templates'
    ref: master
    file: '/prodsec/.oss-scan.yml'

stages:
  - scan
  - release

.prepare_dist: &prepare_dist
  - npm install
  - npm run prepare-release-artifact -- ${PACKAGE_ARG}
  - shasum -a 256 dist/* > dist/checksums.txt

oss-scan:
  stage: scan
  extends: .oss-scan

release:
  before_script:
    - export PACKAGE_FILE="splunk-otel-${CI_COMMIT_REF_NAME:1}.tgz"
    - export PACKAGE_ARG="--package=${PACKAGE_FILE}"
    - export DIR_PACKAGE="--dir_package=../" # directory for package location
  stage: release
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+.*/
  script:
    - *prepare_dist
    - npm run release:github -- ${PACKAGE_ARG} ${DIR_PACKAGE}
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - npm publish ./dist/${PACKAGE_FILE}
    - rm -f ~/.npmrc
  when: manual

esbuild-plugin-release:
  before_script:
    - export PACKAGE_FILE="splunk-otel-esbuild-plugin-node-${CI_COMMIT_REF_NAME:16}.tgz"
    - export PACKAGE_ARG="--package=${PACKAGE_FILE}"
    - export DIR_PACKAGE="--dir_package=../packages/otel-esbuild-plugin/"
  stage: release
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_TAG =~ /^esbuild-plugin-v[0-9]+\.[0-9]+\.[0-9]+.*/
  script:
    - *prepare_dist
    - npm run release:github -- ${PACKAGE_ARG} ${DIR_PACKAGE}
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - npm publish ./dist/${PACKAGE_FILE}
    - rm -f ~/.npmrc
  when: manual

prerelease:
  before_script:
    - export PACKAGE_FILE="splunk-otel-${CI_COMMIT_REF_NAME:12}.tgz"
    - export PACKAGE_ARG="--package=${PACKAGE_FILE}"
  stage: release
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_TAG =~ /^prerelease-v[0-9]+\.[0-9]+\.[0-9]+(?:-.+)?$/
  script:
    - *prepare_dist
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - npm publish --tag prerelease ./dist/${PACKAGE_FILE}
    - rm -f ~/.npmrc
  when: manual
